name: Auto Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm run test:inula-jest | tee ./coverage.txt && exit ${PIPESTATUS[0]}

      - name: Jest Coverage Comment
        id: jest_coverage_comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-path: ./coverage.txt

      # - name: Check Coverage
      #   run: |
      #     if [ ${{ steps.jest_coverage_comment.outputs.coverage }} -lt 80 ]; then
      #       echo "Coverage is less than 80%. Failing the workflow."
      #       exit 1
      #     fi

      - name: Run script
        run: |
          html_content=${{ steps.jest_coverage_comment.outputs.coverageHtml }}

          numbers=$(echo "$html_content" | awk -F '</?td>' '{for (i=2; i<NF; i+=2) print $i}')

          for number in $numbers; do
            if (( $(echo "$number < 50" | bc -l) )); then
              echo "Number $number is less than 50. Workflow failed."
              exit 1
            else
              echo "Number $number is greater than or equal to 50."
            fi
          done
