name: Auto Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm run test:inula-jest | tee ./coverage.txt && exit ${PIPESTATUS[0]}

      - name: Jest Coverage Comment
        id: jest_coverage_comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-path: ./coverage.txt

      - name: Check Total Coverage
        run: |
          if [ ${{ steps.jest_coverage_comment.outputs.coverage }} -lt 75 ]; then
            echo "Coverage is less than 80%. Failing the workflow."
            exit 1
          fi

      - name: Check Coverage Per File
        run: |
          html_content=${{ steps.jest_coverage_comment.outputs.coverageHtml }}

          regex='<td>([0-9]+\.[0-9]+)<\/td>'
          while [[ $html_content =~ $regex ]]; do
              
              decimal="${BASH_REMATCH[1]}"

              if (( $(echo "$decimal < 0" | bc -l) )); then
                  echo "Workflow failed. The decimal $decimal is less than 0."
                  exit 1
              else
                  echo "Decimal $decimal is greater than or equal to 0."
              fi

              html_content="${html_content#*${BASH_REMATCH[0]}}"
          done

          echo "All decimals are greater than or equal to 0. Workflow passed."





